= XibLoc
François Lamboley <francois.lamboley@happn.com>

:happn: https://happn.com
:frizlab: https://github.com/Frizlab

image:https://img.shields.io/badge/platform-macOS%20|%20iOS%20|%20tvOS%20|%20watchOS%20|%20Linux-lightgrey.svg?style=flat[Platforms] link:https://swift.org/package-manager/[image:https://img.shields.io/badge/SPM-compatible-E05C43.svg?style=flat[SPM Compatible]] link:License.txt[image:https://img.shields.io/github/license/happn-app/XibLoc.svg[License]] link:{happn}[image:https://img.shields.io/badge/from-happn-0087B4.svg?style=flat[happn]]

A new format for your locs.

== Installation
Use SPM.

In your `Package.swift`, in the dependencies argument, add:
[source,swift]
----
.package(url: "https://github.com/happn-app/XibLoc.git", from: "1.0.0")
----
and add `XibLoc` to the list of dependencies of your app.

If you`'re using Xcode, add a Swift Package in the settings of your project.

=== Important Note
The repository does have an `xcodeproj` with a shared scheme for debug purposes. The project
might be compatible with Carthage–or not. It is not officially supported but might work for you.

== Linux Support

XibLoc is fully supported on Linux, except we do not allow attributed strings.
`NSAttributedString` is technically supported on Linux, and we could allow it.
However, as of 2021-06-09, Linux does not have either UIFont nor NSFont, same
goes for colors, and thus attributed strings are far less useful. Also,
`AttributedString` does _not_ seems to be supported.

== Important Information for ``XibLoc```'s Devs
If you`'re working on XibLoc on macOS, you have to use the xcodeproj in the project and not
open Package.swift in Xcode. +
The project does not compile because the tests need macOS 10.11 to run when launching the
Package.swift directly. And even when setting the correct minimum version for macOS, some
tests are still not run (ObjC tests) and some tests only work when launched with the xcodeproj
(use resources in a bundle).

== Credits
This project was originally created by {frizlab}[François Lamboley] while working at {happn}[happn].
